### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by howardgriffin** [yilmazdoga/Deep_Residual_Autoencoder_for_Real_Image_Denoising#1]
Nice work, but did you publish the paper of the code？

**Comment by yilmazdoga** [comment]
First of all thank you for your comment. Me and my professor decided not to submit the paper into any conference due to our methods lack of novelty compared to the state-of-the-art methods. You can inspect [DND Dataset Benchmark Page](https://noise.visinf.tu-darmstadt.de/benchmark/) for state-of-the-art methods. To make a comparison between our method and other methods in the benchmark page, I added the PSNR and SSIM values generated using our model and DND dataset below.

PSNR: 38.1075 SSIM: 0.939
